//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public System.Guid Id { get; set; }
        public int CreditCardTypeId { get; set; }
        public string CardNumber { get; set; }
        public short ExpiryMonth { get; set; }
        public short ExpiryYear { get; set; }
        public short SecurityCode { get; set; }
        public bool IsValid { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
    }
}
