//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.DBs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DemoDBEntities : DbContext
    {
        public DemoDBEntities()
            : base("name=DemoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<ActivityType> ActivityTypes { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<CreditCard> CreditCards { get; set; }
        public DbSet<CreditCardType> CreditCardTypes { get; set; }
        public DbSet<Level> Levels { get; set; }
        public DbSet<MemberType> MemberTypes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderHistory> OrderHistories { get; set; }
        public DbSet<OrderStatu> OrderStatus { get; set; }
        public DbSet<OrderStatusType> OrderStatusTypes { get; set; }
        public DbSet<PaymentStatu> PaymentStatus { get; set; }
        public DbSet<PriceType> PriceTypes { get; set; }
        public DbSet<ReferenceType> ReferenceTypes { get; set; }
        public DbSet<Subcategory> Subcategories { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<Term> Terms { get; set; }
        public DbSet<TitleType> TitleTypes { get; set; }
    
        public virtual ObjectResult<RetrieveAllSubjects_Result> RetrieveAllSubjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAllSubjects_Result>("RetrieveAllSubjects");
        }
    }
}
