//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderHistories = new HashSet<OrderHistory>();
            this.OrderStatus = new HashSet<OrderStatu>();
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int ActivityId { get; set; }
        public int PriceTypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> GST { get; set; }
        public decimal PriceIncGST { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal Balance { get; set; }
        public string Memo { get; set; }
        public bool IsSuccess { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Client Client { get; set; }
        public virtual PriceType PriceType { get; set; }
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
        public virtual ICollection<OrderStatu> OrderStatus { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
