//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderActivity
    {
        public System.Guid Id { get; set; }
        public int OrderId { get; set; }
        public int ActivityId { get; set; }
        public int PriceTypeId { get; set; }
        public decimal PriceIncGST { get; set; }
        public decimal TotalIncGST { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Order Order { get; set; }
        public virtual PriceType PriceType { get; set; }
    }
}
