//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public System.Guid Id { get; set; }
        public int OrderId { get; set; }
        public int PaymentStatusId { get; set; }
        public int OrderStatusTypeId { get; set; }
        public bool IsSuccess { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderStatusType OrderStatusType { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
    }
}
