//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.DBs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int PaymentTypeId { get; set; }
        public int OrderId { get; set; }
        public decimal Paid { get; set; }
        public string AuthoredBy { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
